# Copyright 2022 Manna Harbour
# https://github.com/manna-harbour/miryoku

name: 'Build Inputs'
on:
  push:
    branches:
      - master
  workflow_dispatch:
    inputs:
      board:
        description: 'board'
        required: true
        default: 'nice_nano_v2'
      shield:
        description: 'shield'
        required: false
        default: 'corne_left,corne_right'
      alphas:
        description: 'alphas'
        required: false
        default: 'default'
        type: choice
        options:
        - "default"
        - "AZERTY"
        - "BEAKL15"
        - "Colemak"
        - "ColemakDHK"
        - "Dvorak"
        - "Halmak"
        - "QWERTY"
        - "QWERTZ"
        - "Workman"
      nav:
        description: 'nav'
        required: false
        default: 'default'
        type: choice
        options:
        - "default"
        - "invertedT"
        - "vi"
      layers:
        description: 'layers'
        required: false
        default: 'default'
        type: choice
        options:
        - "default"
        - "flip"
      mapping:
        description: 'mapping'
        required: false
        default: 'default'
      custom_config:
        description: 'custom_config'
        required: false
        default: 'default'
      kconfig:
        description: 'kconfig'
        required: false
        default: 'CONFIG_ZMK_POINTING=y'
      branches:
        description: 'branches'
        required: false
        default: 'default'
      modules:
        description: 'modules'
        required: false
        default: 'default'
jobs:
  process-inputs:
    runs-on: ubuntu-latest
    outputs:
      board: ${{ steps.process-inputs.outputs.board }}
      shield: ${{ steps.process-inputs.outputs.shield }}
      alphas: ${{ steps.process-inputs.outputs.alphas }}
      nav: ${{ steps.process-inputs.outputs.nav }}
      layers: ${{ steps.process-inputs.outputs.layers }}
      mapping: ${{ steps.process-inputs.outputs.mapping }}
      custom_config: ${{ steps.process-inputs.outputs.custom_config }}
      kconfig: ${{ steps.process-inputs.outputs.kconfig }}
      branches: ${{ steps.process-inputs.outputs.branches }}
      modules: ${{ steps.process-inputs.outputs.modules }}
    steps:
      - name: Process inputs
        id: process-inputs
        run: |
          set-output()
          {
            json=`echo "$2" | jq -cnR 'inputs | split(",";"")'`
            echo "$1=$json" >> $GITHUB_OUTPUT
          }

          board="${{ github.event.inputs.board || 'nice_nano_v2' }}"
          shield="${{ github.event.inputs.shield || 'corne_left,corne_right' }}"
          alphas="${{ github.event.inputs.alphas || 'default' }}"
          nav="${{ github.event.inputs.nav || 'default' }}"
          layers="${{ github.event.inputs.layers || 'default' }}"
          mapping="${{ github.event.inputs.mapping || 'default' }}"
          custom_config="${{ github.event.inputs.custom_config || 'default' }}"
          kconfig="${{ github.event.inputs.kconfig || 'CONFIG_ZMK_POINTING=y' }}"
          branches="${{ github.event.inputs.branches || 'default' }}"
          modules="${{ github.event.inputs.modules || 'default' }}"

          set-output-json "board" "$board"
          set-output-json "shield" "$shield"
          set-output-json "alphas" "$alphas"
          set-output-json "nav" "$nav"
          set-output-json "layers" "$layers"
          set-output-json "mapping" "$mapping"
          set-output-json "custom_config" "$custom_config"
          set-output-json "kconfig" "$kconfig"
          set-output-json "branches" "$branches"
          set-output-json "modules" "$modules"
  build:
    uses: ./.github/workflows/main.yml
    secrets: inherit
    needs: process-inputs
    with:
      board: ${{ needs.process-inputs.outputs.board }}
      shield: ${{ needs.process-inputs.outputs.shield }}
      alphas: ${{ needs.process-inputs.outputs.alphas }}
      nav: ${{ needs.process-inputs.outputs.nav }}
      layers: ${{ needs.process-inputs.outputs.layers }}
      mapping: ${{ needs.process-inputs.outputs.mapping }}
      custom_config: ${{ needs.process-inputs.outputs.custom_config }}
      kconfig: ${{ needs.process-inputs.outputs.kconfig }}
      branches: ${{ needs.process-inputs.outputs.branches }}
      modules: ${{ needs.process-inputs.outputs.modules }}
